import Navbar from '@components/Navbar';
import type { Metadata } from 'next'
import { Inter } from 'next/font/google';
import Provider from '@components/Provider'
import '@styles/css/index.css';

export const metadata: Metadata = {
  title: 'YT Notes',
  description: 'Generated by create next app',
}

const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter', // Set CSS variable
});

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en" className={inter.variable}>
      <body className='Root' style={{ margin: 0 }}>
        <Provider session={undefined}>
          <Navbar />
          <main className='App'>
            {children}
          </main>
        </Provider>
      </body>
    </html> 
  )
}
